# Generated by Django 4.2.5 on 2023-09-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_category_cropcategory_disease_productcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='disease_name',
            field=models.CharField(default='hi', max_length=50),
            preserve_default=False,
        ),
    ]
